//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advent2017.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advent2017.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon christmastree {
            get {
                object obj = ResourceManager.GetObject("christmastree", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31,2,85,1,80,109,35,63,98,255,0,13,105,254,128,33.
        /// </summary>
        public static string Day10Input {
            get {
                return ResourceManager.GetString("Day10Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to se,se,se,se,s,s,nw,s,sw,se,se,sw,sw,sw,se,nw,sw,nw,se,nw,nw,s,nw,nw,n,ne,n,n,sw,n,n,n,nw,n,ne,n,n,n,n,n,s,ne,se,nw,n,sw,n,n,ne,ne,n,n,s,n,n,n,ne,n,n,ne,ne,ne,ne,ne,ne,ne,sw,ne,nw,ne,se,ne,ne,se,ne,ne,sw,ne,nw,n,se,nw,se,ne,se,ne,nw,se,se,se,se,se,se,se,se,se,se,ne,ne,se,se,se,s,ne,se,se,se,se,s,ne,se,se,se,se,se,s,s,se,nw,se,se,s,s,se,s,se,s,se,ne,s,s,s,s,s,s,s,s,se,s,s,n,sw,s,s,s,n,s,s,sw,s,s,s,s,s,nw,s,s,sw,s,s,s,s,ne,s,sw,sw,sw,sw,se,nw,s,s,s,nw,s,s,sw,sw,sw,s,nw,sw,sw,s,s,s,nw,sw,se,sw,s,s,sw,sw,s,sw,ne [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day11Input {
            get {
                return ResourceManager.GetString("Day11Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 &lt;-&gt; 1352, 1864
        ///1 &lt;-&gt; 430
        ///2 &lt;-&gt; 1202, 1416
        ///3 &lt;-&gt; 303, 363, 635
        ///4 &lt;-&gt; 1041, 1383
        ///5 &lt;-&gt; 143, 1513
        ///6 &lt;-&gt; 6
        ///7 &lt;-&gt; 619
        ///8 &lt;-&gt; 167, 1246, 1822
        ///9 &lt;-&gt; 577, 1274, 1347
        ///10 &lt;-&gt; 10, 899
        ///11 &lt;-&gt; 790
        ///12 &lt;-&gt; 606
        ///13 &lt;-&gt; 1134, 1894
        ///14 &lt;-&gt; 539, 1974
        ///15 &lt;-&gt; 683, 1783
        ///16 &lt;-&gt; 438, 1235
        ///17 &lt;-&gt; 17
        ///18 &lt;-&gt; 760, 1162
        ///19 &lt;-&gt; 1146
        ///20 &lt;-&gt; 678, 1235, 1397, 1911
        ///21 &lt;-&gt; 127, 615, 980
        ///22 &lt;-&gt; 22, 187
        ///23 &lt;-&gt; 192, 552
        ///24 &lt;-&gt; 169
        ///25 &lt;-&gt; 471
        ///26 &lt;-&gt; 1030, 1329, 1333
        ///27 &lt;-&gt; 1404
        ///28 &lt;-&gt; 1249
        ///29 &lt;-&gt; 1755
        ///30 &lt;-&gt; 198
        ///31  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day12Input {
            get {
                return ResourceManager.GetString("Day12Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0: 4
        ///1: 2
        ///2: 3
        ///4: 5
        ///6: 8
        ///8: 4
        ///10: 6
        ///12: 6
        ///14: 6
        ///16: 10
        ///18: 6
        ///20: 12
        ///22: 8
        ///24: 9
        ///26: 8
        ///28: 8
        ///30: 8
        ///32: 12
        ///34: 12
        ///36: 12
        ///38: 8
        ///40: 10
        ///42: 14
        ///44: 12
        ///46: 14
        ///48: 12
        ///50: 12
        ///52: 12
        ///54: 14
        ///56: 14
        ///58: 14
        ///60: 12
        ///62: 14
        ///64: 14
        ///68: 12
        ///70: 14
        ///74: 14
        ///76: 14
        ///78: 14
        ///80: 17
        ///82: 28
        ///84: 18
        ///86: 14.
        /// </summary>
        public static string Day13Input {
            get {
                return ResourceManager.GetString("Day13Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stpzcrnm.
        /// </summary>
        public static string Day14Input {
            get {
                return ResourceManager.GetString("Day14Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A 618
        ///B 814.
        /// </summary>
        public static string Day15Input {
            get {
                return ResourceManager.GetString("Day15Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x3/15,pc/l,x13/9,pe/f,x3/14,s2,x8/10,s15,x4/0,s4,pn/k,x9/13,s5,x3/6,s14,x9/14,s10,x5/13,ph/j,x11/8,s11,x0/15,pa/d,x3/1,pg/l,x6/5,s11,x12/13,pj/d,s1,x11/0,pm/f,x4/15,s5,x3/5,ph/c,x13/12,s15,x10/6,s11,x11/2,po/i,x0/9,s11,x11/15,s13,x7/3,s4,x12/13,s5,x14/11,pc/e,x1/7,s6,x3/5,pk/j,x7/0,ph/f,x10/8,s8,x13/6,pl/o,x8/0,s2,x4/13,pn/c,x1/12,po/g,x15/4,s8,x10/12,s4,x11/0,pp/d,x7/14,s6,pf/e,x2/15,pc/b,s14,x5/10,s12,x7/8,s4,x0/1,s12,x12/3,s6,pd/o,s9,x14/7,s5,pl/g,s11,po/m,x12/8,s11,x7/0,s1,x1/14,pe/c,x9/2,pa/j,s14,x8/1, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day16Input {
            get {
                return ResourceManager.GetString("Day16Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Day17Input {
            get {
                return ResourceManager.GetString("Day17Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 73857646862514444739979151237829725363437326575178346717594627954612137824283429318961816955789962743213174192423595347839573729329537743363381184889671727276518624988381953176542897975586834585111269962179533228172293723734558621778444784433918354845915252356518634648911779272449549258277867994365365925613742692994747383212935753858994384465585692412362787797799835879124313954752447965388883732871869216474268662377567373427319767639594991499963155915847161221991832952774398729113713139245944867664794385444 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day1Input {
            get {
                return ResourceManager.GetString("Day1Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 86	440	233	83	393	420	228	491	159	13	110	135	97	238	92	396
        ///3646	3952	3430	145	1574	2722	3565	125	3303	843	152	1095	3805	134	3873	3024
        ///2150	257	237	2155	1115	150	502	255	1531	894	2309	1982	2418	206	307	2370
        ///1224	343	1039	126	1221	937	136	1185	1194	1312	1217	929	124	1394	1337	168
        ///1695	2288	224	2667	2483	3528	809	263	2364	514	3457	3180	2916	239	212	3017
        ///827	3521	127	92	2328	3315	1179	3240	695	3144	3139	533	132	82	108	854
        ///1522	2136	1252	1049	207	2821	2484	413	2166	1779	162	2154	158	2811	164	2632
        ///95	579	1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day2Input {
            get {
                return ResourceManager.GetString("Day2Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Day3Part2 {
            get {
                object obj = ResourceManager.GetObject("Day3Part2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oaoe rxeq vssdqtu xrk cjv yaoqp loo
        ///mveua dogbam szydvri hyzk lbega abzqw xwjn wniug kwbre
        ///npaoy uivpxwd oynpa rcdk uixpvdw
        ///yserir iikzcm ieuroca iuwcfov rvb giti crdpdcv mxpps
        ///spyuhgo lucasl ucllsa bymnjig yflbv nxitmlf
        ///xlxyhwz xla mpye fvjegwg fezlfrt inetrh vhg xpvstx ydhvq
        ///xgue cvtmh myg ontvvyw ygm oqzrdrw
        ///srdfsjf dli kccb kauk kauk apa doefc cdffkhh cdffkhh
        ///msizb elqiov lqn epamk onmnlst baawab ncafwaf jrataml iyzhy svycuec
        ///wdzqpcn dkgdumv wdzqpcn qxdmwib cjsigi bgcihgh fmua
        ///kpvbzf kpvbzf sv [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day4Input {
            get {
                return ResourceManager.GetString("Day4Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0
        ///0
        ///2
        ///0
        ///0
        ///0
        ///-5
        ///-5
        ///-4
        ///1
        ///-5
        ///1
        ///-1
        ///-7
        ///-1
        ///-2
        ///-14
        ///-5
        ///-5
        ///-4
        ///1
        ///0
        ///-9
        ///2
        ///-4
        ///-1
        ///-18
        ///-3
        ///-12
        ///-10
        ///-22
        ///-18
        ///-28
        ///-11
        ///-33
        ///0
        ///-22
        ///-14
        ///2
        ///-1
        ///-14
        ///-4
        ///-5
        ///-40
        ///-33
        ///-38
        ///-12
        ///-29
        ///-47
        ///-14
        ///2
        ///-34
        ///-26
        ///-10
        ///-47
        ///-20
        ///-24
        ///-12
        ///-12
        ///-39
        ///-43
        ///-56
        ///-36
        ///-52
        ///-38
        ///-8
        ///-53
        ///-53
        ///-31
        ///-29
        ///-53
        ///-20
        ///-71
        ///-14
        ///-61
        ///-25
        ///-70
        ///-37
        ///-32
        ///-30
        ///-10
        ///-78
        ///-42
        ///-59
        ///-40
        ///-19
        ///-41
        ///-40
        ///-81
        ///-9
        ///-69
        ///-49
        ///-39
        ///-12
        ///-6
        ///-18
        ///-93
        ///-14
        ///-46
        ///-88
        ///-72
        ///-84
        ///-51
        ///-79
        ///-23
        ///-96
        ///-72
        ///-73
        ///-38
        ///-19
        ///-7
        ///-90
        ///-37
        ///-28
        ///-18
        ///-84
        ///-42
        ///-115
        ///-33
        ///-100
        ///-99
        ///-50
        ///-37
        ///-90
        ///-60
        ///-19
        ///-59
        ///-107
        ///0
        ///-78
        ///-40
        ///-82
        ///-114
        ///-33
        ///-24
        ///-105
        ///-22
        ///-20
        ///-39
        ///-45 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day5Input {
            get {
                return ResourceManager.GetString("Day5Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apcztdj (61)
        ///ulovosc (61) -&gt; buzjgp, iimyluk
        ///awpvs (88)
        ///ykbjhi (14)
        ///gxvketg (49)
        ///gpmvdo (78) -&gt; jjixrr, zacrh, smylfq, fdvtn
        ///nwpmqu (6025) -&gt; aytrde, grokih, pjqaa, nzzved
        ///keiakhg (50)
        ///vkrlz (22)
        ///myzkj (40)
        ///zkzpbbp (46)
        ///eaumqtc (288) -&gt; tvmvvxn, ckcpovl
        ///htlovrb (1662) -&gt; atxtq, ewsqqum, mjwviex
        ///aoxky (53873) -&gt; orzwmml, tcvtul, ygszhn
        ///uhfiqwc (81)
        ///gziopi (189) -&gt; hboommj, glbipl, evojkum
        ///rjksjq (66)
        ///rwyzrl (1434) -&gt; geiethw, nclvb, riphudi
        ///gmusjd (98)
        ///vjmwzo (76)
        ///xymsu (153) -&gt; kbgmlab, yjjewyt
        ///mgiumh (64)
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day7Input {
            get {
                return ResourceManager.GetString("Day7Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v inc 523 if t == 6
        ///qen dec -450 if lht != 10
        ///jyg dec -378 if lb != -6
        ///k inc -994 if z &lt; 6
        ///gjr inc -698 if hbq &lt; 9
        ///gjr inc -422 if pv &lt;= 9
        ///lb dec -17 if t != -3
        ///pv dec -627 if u &gt; -3
        ///pv inc -84 if jpc != 2
        ///erl inc -531 if kfw &gt; -10
        ///kfw dec -751 if tu != 9
        ///erl dec -536 if g != 0
        ///tu inc -813 if ee &gt;= 0
        ///mpj dec -929 if u &lt; -1
        ///uz inc 565 if lb &gt; 8
        ///ml inc -357 if uz == 565
        ///qen inc 800 if erl &gt; -540
        ///lht dec -238 if tu == -811
        ///z dec 16 if hbq &gt;= 10
        ///v inc 308 if osr &lt; 4
        ///u dec -628 if u &lt; 7
        ///u de [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day8Input {
            get {
                return ResourceManager.GetString("Day8Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{{{{&lt;!!!&gt;},&lt;!e!!!&apos;ue!o!!!&gt;&quot;oo&lt;u!}&lt;&lt;{&gt;},{{{}},{&lt;!&gt;},&lt;&apos;&gt;,{&lt;!!&quot;!!!&gt;&quot;u!!!&gt;!!!&gt;,&lt;&quot;!&gt;,&lt;!&gt;},&lt;}!!}!!!&gt;{&gt;}},{{&lt;&quot;!&gt;}}!&apos;!!u!!!!e!!!&gt;&gt;}}}},{{{&lt;!&gt;&gt;}},{{{&lt;{{!!,&gt;},{&lt;u!!e&apos;!&gt;},&lt;&gt;}}},{&lt;,o!!!&quot;&quot;a!&gt;},&lt;!&gt;},&lt;&lt;}&gt;,{&lt;!!!!,,!&gt;,&lt;!&gt;},&lt;&quot;!!!&gt;u&gt;}}},{{{&lt;}{!&lt;{i!&gt;&gt;}},{{}},{{},&lt;!&gt;,&lt;!&gt;,&lt;!&gt;!!,&lt;!!!!{}!!i&gt;}}},{{},{{{}}},{{&lt;ae{&gt;,{}}},{{&lt;!!!!&quot;&gt;,&lt;{&apos;}!!},&lt;!&gt;a,!&gt;!!!&gt;{!!e&gt;},{{&lt;!ao!!i!&apos;!&gt;,&lt;!!o&gt;,&lt;&apos;e}!!!&gt;!!!&gt;e&apos;!!u{&gt;},&lt;&quot;,&apos;i!!!&gt;{&gt;},{&lt;uai,!!{!&gt;},&lt;uu!!e&gt;}}},{{{{{&lt;!!,a!&gt;&gt;}}}},{},{{{{{{},{{&lt;au&lt;,!!iuu!!!!!&gt;,&lt;&gt;}}},{&lt;i!&gt;,&lt;!&gt;},&lt;!!&apos;iu{!!o&quot;{i,i}!{{&gt;}},{},{{&lt;a!&gt;a&quot;!! [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day9Input {
            get {
                return ResourceManager.GetString("Day9Input", resourceCulture);
            }
        }
    }
}
